openapi: 3.0.3

info:
  title: FinCore API
  description: API for financial operations
  version: "1.0.0"
  contact:
    name: Domey Benjamin
    email: domeybenjamin1@gmail.com
    url: https://www.linkedin.com/in/benjamin-armah-kesey-domey/

servers:
  - url: http://localhost:5002
    description: Local development
  - url: "https://fincore-staging.fly.dev"
    description: Staging API
  - url: "https://fincore.fly.dev"
    description: Production API

paths:
  /:
    get:
      summary: Health check
      responses:
        '200':
          description: A successful response

  /api/v1/clients:
    post:
      summary: Create a new client
      requestBody:
        content:
          application/json:
            schema:
              $ref: ./schemas/client_post.yaml
      responses:
        '201':
          description: Return the created client
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: ./schemas/client.yaml
        '400':
          description: Bad Request.
          content:
            application/json:
              schema:
                $ref: ./schemas/common/bad_request.yaml
        '422':
          description: Parameter Validation errors
          content:
            application/json:
              schema:
                $ref: ./schemas/validate/client_post_validate.yaml
        '500':
          description: Internal Server Error
      tags:
        - Client

  /api/v1/clients/me:
    get:
      summary: Get the current client's information
      responses:
        '200':
          description: Return the current client's information
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: ./schemas/client.yaml
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
      tags:
        - Client

  /api/v1/accounts:
    post:
      summary: Create a new account
      requestBody:
        content:
          application/json:
            schema:
              $ref: ./schemas/account_post.yaml
      responses:
        '201':
          description: Return the created account
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: ./schemas/account.yaml
        '400':
          description: Bad Request.
          content:
            application/json:
              schema:
                $ref: ./schemas/common/bad_request.yaml
        '422':
          description: Parameter Validation errors
          content:
            application/json:
              schema:
                $ref: ./schemas/validate/account_post_validate.yaml
        '500':
          description: Internal Server Error
      tags:
        - Account

    get:
      summary: List all accounts
      parameters:
        - $ref: ./parameters/page.yaml
        - $ref: ./parameters/page_size.yaml
        - $ref: ./parameters/order.yaml
        - $ref: ./parameters/order_by.yaml
        - $ref: ./parameters/query.yaml
        - $ref: ./parameters/search_fields.yaml
        - $ref: ./parameters/start_date.yaml
        - $ref: ./parameters/end_date.yaml
        - $ref: ./parameters/populate_account.yaml
        - $ref: ./parameters/is_contra.yaml
        - $ref: ./parameters/is_group.yaml
        - $ref: ./parameters/account_type.yaml
        - $ref: ./parameters/parent_account_id.yaml
      responses:
        '200':
          description: Return a list of accounts with pagination info
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: ./schemas/account.yaml
                  meta:
                    $ref: ./schemas/common/meta.yaml
        '400':
          description: Bad Request.
          content:
            application/json:
              schema:
                $ref: ./schemas/common/bad_request.yaml
        '422':
          description: Parameter Validation errors
          content:
            application/json:
              schema:
                $ref: ./schemas/validate/account_list_validate.yaml
        '500':
          description: Internal Server Error
      tags:
        - Account

  /api/v1/accounts/{account_id}:
    patch:
      summary: Update an existing account
      parameters:
        - $ref: ./parameters/account_id.yaml
      requestBody:
        content:
          application/json:
            schema:
              $ref: ./schemas/account_patch.yaml
      responses:
        '200':
          description: Return the updated account
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: ./schemas/account.yaml
        '400':
          description: Bad Request.
          content:
            application/json:
              schema:
                $ref: ./schemas/common/bad_request.yaml
        '422':
          description: Parameter Validation errors
          content:
            application/json:
              schema:
                $ref: ./schemas/validate/account_patch_validate.yaml
        '500':
          description: Internal Server Error
      tags:
        - Account
    
    delete:
      summary: Delete an existing account
      parameters:
        - $ref: ./parameters/account_id.yaml
      responses:
        '204':
          description: Account successfully deleted
        '400':
          description: Bad Request.
          content:
            application/json:
              schema:
                $ref: ./schemas/common/bad_request.yaml
        '422':
          description: Parameter Validation errors
          content:
            application/json:
              schema:
                $ref: ./schemas/validate/account_delete_validate.yaml
        '500':
          description: Internal Server Error
      tags:
        - Account

    get:
      summary: Get single account details
      parameters:
        - $ref: ./parameters/account_id.yaml
        - $ref: ./parameters/populate_account.yaml
      responses:
        '200':
          description: Return the account details
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: ./schemas/account.yaml
        '400':
          description: Bad Request.
          content:
            application/json:
              schema:
                $ref: ./schemas/common/bad_request.yaml
        '422':
          description: Parameter Validation errors
          content:
            application/json:
              schema:
                $ref: ./schemas/validate/account_get_validate.yaml
        '500':
          description: Internal Server Error
      tags:
        - Account
