openapi: 3.0.4
info:
  title: FinCore API
  description: API for financial operations
  version: "1.0.0"
servers:
  - url: http://localhost:5002
paths:
  /hello:
    get:
      summary: Returns a greeting
      responses:
        '200':
          description: A successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Hello, world!
